---
- name: Save the add_shard_to_cluster script
  template:
    src: templates/add_shard_to_cluster.js.j2
    dest: /tmp/add_shard_to_cluster.js
  run_once: true

- name: Run the add_shard_to_cluster script
  shell: >
    mongo
    --host {{ bindIp }}
    --port {{ bindPort }}
    < /tmp/add_shard_to_cluster.js
  run_once: true
  become: true
  register: result
  until: result.rc == 0
  retries: 5
  delay: 3
  when: true
