---
- name: Set config_db variable
  set_fact:
    config_db: "{{ cfg_server.name }}/{{ cfg_servers|join(',') }}"

- name: Set config_db variable
  set_fact:
    rs_servers: "{{ config_servers | default([]) }}"
  when: cluster_role == "config"

- name: Set config_db variable
  set_fact:
    rs_servers: "{{ shard_servers | default([]) }}"
  when: cluster_role != "config"

- name: Set bind port
  set_fact:
    bindPort: "{{ ports[cluster_role] }}"
