---
- name: stat for mongodb
  stat:
    path: /etc/systemd/system/mongodb
  register: stat_db

- name: stat for mongod
  stat:
    path: "/etc/systemd/system/mongod-{{ cluster_role }}.service"
  register: stat_d

- name: stat for mongos
  stat:
    path: "/etc/systemd/system/mongos-{{ cluster_role }}.service"
  register: stat_s

- name: Stop the daemon service
  become: true
  service:
    name: mongod-{{ cluster_role }}
    state: stopped
  when:
    - stat_db.stat.exists

- name: Stop the daemon service
  become: true
  service:
    name: mongod-{{ cluster_role }}
    state: stopped
  when:
    - stat_d.stat.exists

- name: Stop the shard service
  become: true
  service:
    name: mongos-{{ cluster_role }}
    state: stopped
  when:
    - stat_s.stat.exists
